### ISSUE TITLE
File icons loaded over HTTP, resulting in Mixed Content Warnings. 

### ISSUE THREAD

**Issue by jstockwin** [Students4Students/KeystoneJS-Website#1]
The files are currently served by [http://www.stdicon.com/](http://www.stdicon.com/). I have made [an issue](https://github.com/ptarjan/stdicon/issues/2) there requesting that they use SSL. Failing this, I will try and find another source, or start hosting an icon pack myself.

**Comment by Benny-** [comment]
Have you ever found another icon source?

**Comment by jstockwin** [comment]
@Benny- I did not, but haven't tried very hard. If you find any, please let me know!

**Comment by Benny-** [comment]
@jstockwin: Hi, this one has HTTPS support: https://wgenial.github.io/mimetypeicons/
